# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - gosec
    - unconvert
    - dupl
    - misspell
    - lll
    - nakedret
    - prealloc
    - copyloopvar
    - gocritic
    - gochecknoinits
    - gocyclo
    - godot
    - godox
    - err113
    - mnd
    - goprintffuncname
    - nestif
    - noctx
    - nolintlint
    - revive
    - stylecheck
    - testpackage
    - tparallel
    - unparam
    - whitespace

  disable:
    - exhaustive
    - gochecknoglobals
    - gocognit
    - goconst
    - funlen
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  govet:
    enable-all: true
    shadow: true
    
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/gifflet/ccmd
    
  gocyclo:
    min-complexity: 15
    
  dupl:
    threshold: 100
    
  misspell:
    locale: US
    
  lll:
    line-length: 120
    tab-width: 4
    
  nakedret:
    max-func-lines: 30
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
    
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - whyNoLint
      
  godox:
    keywords:
      - TODO
      - FIXME
      - BUG
      - HACK
      - OPTIMIZE
      
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '10'
      - '100'

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - testdata
  exclude-files:
    - ".*_test.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - mnd
        - err113
        
    # Ignore TODO/FIXME comments in specific files
    - path: internal/model/
      linters:
        - godox
        
    - path: internal/repository/
      linters:
        - godox
        
    - path: cmd/
      linters:
        - forbidigo
        
    - text: "Subprocess launch(ed with variable|ing should be audited)"
      linters:
        - gosec
        
    - text: "weak cryptographic primitive"
      linters:
        - gosec
        
    # Ignore error checks on fmt.Scanln in UI code
    - path: "(cmd/|output/)"
      text: "Error return value of `fmt.Scanln` is not checked"
      linters:
        - errcheck
        
    # Ignore unused parameter warnings for cobra command functions
    - path: cmd/
      text: "unused-parameter"
      linters:
        - revive
        
    # Ignore fieldalignment warnings - we prioritize readability over memory optimization
    - linters:
        - govet
      text: "fieldalignment:"
      
    # Ignore shadow warnings in specific cases
    - linters:
        - govet
      text: "shadow: declaration of \"err\""
      
    # Ignore package comment warnings
    - linters:
        - revive
        - stylecheck
      text: "should have a package comment"
      
    # Ignore comment punctuation warnings
    - linters:
        - godot
      text: "Comment should end in a period"
      
    # Ignore specific errcheck warnings in output functions
    - path: internal/output/
      linters:
        - errcheck
      text: "Error return value of `fmt.Fprintf` is not checked"
      
    # Ignore errcheck warnings for fmt.Fprint in logger
    - path: pkg/logger/logger.go
      linters:
        - errcheck
      text: "Error return value of `fmt.Fprint` is not checked"
      
    # Ignore errcheck warnings for fmt.Fprintf in errors handler
    - path: pkg/errors/handler.go
      linters:
        - errcheck
      text: "Error return value of `fmt.Fprintf` is not checked"
      
    # Ignore err113 for simple error cases
    - linters:
        - err113
      text: "do not define dynamic errors"
      
    # Ignore exported type naming warnings
    - linters:
        - revive
      text: "exported.*should have comment or be unexported"
      
    # Ignore nestif complexity
    - linters:
        - nestif
      text: "has complex nested blocks"
      
    # Ignore magic numbers in specific contexts
    - linters:
        - mnd
      text: "Magic number"
      
    # Ignore cyclomatic complexity warnings
    - linters:
        - gocyclo
      text: "cyclomatic complexity"
      
    # Ignore huge param warnings
    - linters:
        - gocritic
      text: "hugeParam:"
        
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
  fix: false